apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-app-token-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "90s"
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /auth/v1/token
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 81