apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  db-user: {{ .Values.dbUser | b64enc }}
  db-pass: {{ .Values.dbPass | b64enc }}
  db-host: {{ .Values.dbHost | b64enc }}
  db-port: {{ .Values.dbPort | b64enc }}
  db-name: {{ .Values.dbName | b64enc }}
