apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-healthcheck-deployment
  labels:
    app: php-healthcheck
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-healthcheck
  template:
    metadata:
      labels:
        app: php-healthcheck
    spec:
      containers:
        - name: php-healthcheck
          image: danielpalm/php-healthcheck-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 5
