apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikube-service
  template:
    metadata:
      labels:
        app: minikube-service
    spec:
      containers:
        - name: minikube-service
          image: danielpalm/php-healthcheck-service:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
