apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-service
  namespace: m
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikube-service
  template:
    metadata:
      labels:
        app: minikube-service
    spec:
      containers:
        - name: minikube-service
          image: danielpalm/php-healthcheck-service:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
