apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minikube-ingress
  namespace: m
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/([^/]+)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: minikube-service
                port:
                  number: 80
          - path: /health
            pathType: ImplementationSpecific
            backend:
              service:
                name: minikube-service
                port:
                  number: 80
