apiVersion: v1
kind: Service
metadata:
  name: minikube-service
  namespace: m
spec:
  selector:
    app: php-healthcheck
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
