image:
  repository: my_restful_crud
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
  tls: []