persistence:
  existingClaim: postgresql-pv-claim
  size: 10Gi
  accessModes:
    - ReadWriteOnce

postgresql:
  postgresqlDatabase: mydatabase
  postgresqlUsername: myuser
  postgresqlPassword: mypassword
