persistence:
  existingClaim: postgresql-pv-claim

volumePermissions:
  enabled: true

postgresql:
  postgresqlUsername: user
  postgresqlPassword: password
  postgresqlDatabase: postgres
  postgresqlPort: 5432
